VALIDATOR_INDEXES:
  - 1
  - 2
  - 3
  - 4
  - 5

START_DATE: "2020-12-01"
END_DATE: "2020-12-31"  # Inclusive

# Any CoinGecko-supported currency
CURRENCY: "EUR"

BEACON_NODE:
  # Enter the hostname or IP address of the beacon node (e.g. localhost or 192.168.1.123)
  HOST: localhost
  # Enter the HTTP/RPC port of the beacon node
  # Defaults - Lighthouse 5052, Prysm 3500, Teku 5051, Nimbus 9190
  PORT: 5052
  # Set this to True if running a Prysm beacon node (it uses a different API)
  # Should be set to False for Lighthouse, Teku, Nimbus
  PRYSM_API: False
  # Set this to True if running a Nimbus beacon node (it uses a different API)
  # Should be set to False for Lighthouse, Prysm, Teku
  NIMBUS_API: False
  # The amount of concurrent requests to make to the beacon node
  # (making more than 1 request at once makes things faster, but is
  # also more demanding on your beacon node)
  CONCURRENT_REQUESTS: 5
